// Class automatically generated by Dev-C++ New Class wizard

#ifndef LZ77_ENCODER_H
#define LZ77_ENCODER_H

#include "constants.h"
#include "global_functions.cpp"
#include <deque>

#define INDEX_3D(x,y,z) x + 256 * (y + 256 * z)

class LZ77_Encoder {
private:
	//indice del primo elemento del look ahead buffer
	long lh_index;
	long perc, prevperc;

	typedef std::deque<int> int_deque;
	int_deque* tdArray;

public:
	const char* original;

	long original_length;

	void update_key_array(int size);
	long last_update_index;
	// class constructor
	LZ77_Encoder(char* _original, int o_size);
	// class destructor
	~LZ77_Encoder();

	//returns false if the end of the string is reached, false otherwise
	bool hasMore();
	//returns the next element (literal or length-distance pair)
	lz77_r getNext();

	void print_perc();

	void reset();
};

#endif // LZ77_ENCODER_H
