// Class automatically generated by Dev-C++ New Class wizard

#ifndef LZ77_ENCODER_H
#define LZ77_ENCODER_H

#define SEARCH_BUFFER_LENGTH 5
#define LOOK_AHEAD_BUFFER_LENGTH 6

#include "constants.h"

class LZ77_Encoder
{
	public:
		// class constructor
		LZ77_Encoder();
		// class destructor
		~LZ77_Encoder();
		
		lz77_r* encode(std::string original,int* encoded_length);
		std::string decode(lz77_r* encoded,int length);
};

#endif // LZ77_ENCODER_H
